-- hds header_start
--
-- VHDL Architecture my_uart.clk_100us.rtl
--
-- Created:
--          by - scg.UNKNOWN (SCG-PC)
--          at - 17:44:44 22/05/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY clk_100us IS
port(rst,clk,en: in std_logic;
       clk_out: out std_logic);
-- Declarations

END clk_100us ;

-- hds interface_end
ARCHITECTURE rtl OF clk_100us IS
signal t: unsigned(25 downto 0);
BEGIN
process(rst,clk)
begin
if(rst='0')then 
t<=(others=>'0');
elsif(rising_edge(clk))then
   if(en='1')then
   -- no. of clock per sec (27MHZ=27,000,000 clk/sec)
       if(t<20)then
          t<=t+1;
	-- half the no. of clk per sec (27/2) but preferable to calc it from simulation
          if(t<=10)then
          clk_out<='1';
          elsif( t>10)then
          clk_out<='0';
          end if;
		  else t<=(others=>'0');
       end if;
   else t<=(others=>'0');
        clk_out<='0'; 
   end if;
   
end if;
end process;
END rtl;
