-- hds header_start
--
-- VHDL Architecture test_synopsysieee.mul_signed.rtl
--
-- Created:
--          by - hp.UNKNOWN (LAPTOP-DAO6M56I)
--          at - 12:10:27 06/17/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY mul_conv4 IS
port( rst,clk: in std_logic;
      IN_filter_clk: in std_logic_vector( 8 downto 0);
     IN_image_clk: in std_logic_vector( 7 downto 0);
    
     x: out std_logic_vector( 21 downto 0));
 
-- Declarations

END mul_conv4 ;

-- hds interface_end
ARCHITECTURE rtl OF mul_conv4 IS
signal a :unsigned( 8 downto 0);

signal p1,p2,p3,p4,p5,p6,p7,p8,p9 :unsigned( 17 downto 0);
signal p11,p22,p33,p44,p55,p66,p77,p88,p99 :unsigned( 17 downto 0);
signal res1,res2: unsigned (17 downto 0);
BEGIN
a<=unsigned('0'&IN_image_clk);
p1<=(others=>'0') when (rst='0' or a(0)='0') else unsigned("111111111"&IN_filter_clk);
p2<=(others=>'0') when (rst='0' or a(1)='0') else unsigned("11111111"&IN_filter_clk&'0');
p3<=(others=>'0') when (rst='0' or a(2)='0') else unsigned("1111111"&IN_filter_clk&"00");
p4<=(others=>'0') when (rst='0' or a(3)='0') else unsigned("111111"&IN_filter_clk&"000");
p5<=(others=>'0') when (rst='0' or a(4)='0') else unsigned("11111"&IN_filter_clk&"0000");
p6<=(others=>'0') when (rst='0' or a(5)='0') else unsigned("1111"&IN_filter_clk&"00000");
p7<=(others=>'0') when (rst='0' or a(6)='0') else unsigned("111"&IN_filter_clk&"000000");
p8<=(others=>'0') when (rst='0' or a(7)='0') else unsigned("11"&IN_filter_clk&"0000000");
p9<=(others=>'0') when (rst='0' or a(8)='0') else unsigned("1"&IN_filter_clk&"00000000");  
  

p11<=(others=>'0') when (rst='0' or a(0)='0') else unsigned("000000000"&IN_filter_clk);
p22<=(others=>'0') when (rst='0' or a(1)='0') else unsigned("00000000"&IN_filter_clk&'0');
p33<=(others=>'0') when (rst='0' or a(2)='0') else unsigned("0000000"&IN_filter_clk&"00");
p44<=(others=>'0') when (rst='0' or a(3)='0') else unsigned("000000"&IN_filter_clk&"000");
p55<=(others=>'0') when (rst='0' or a(4)='0') else unsigned("00000"&IN_filter_clk&"0000");
p66<=(others=>'0') when (rst='0' or a(5)='0') else unsigned("0000"&IN_filter_clk&"00000");
p77<=(others=>'0') when (rst='0' or a(6)='0') else unsigned("000"&IN_filter_clk&"000000");
p88<=(others=>'0') when (rst='0' or a(7)='0') else unsigned("00"&IN_filter_clk&"0000000");
p99<=(others=>'0') when (rst='0' or a(8)='0') else unsigned("0"&IN_filter_clk&"00000000");


res1<= (others=>'0') when (rst='0') else p1+p2+p3+p4+p5+p6+p7+p8+p9;
res2<= (others=>'0') when (rst='0') else p11+p22+p33+p44+p55+p66+p77+p88+p99;

process(clk,rst)begin
 if(rst='0')then
 x<=(others=>'0');
elsif(rising_edge(clk))then 

  if(IN_filter_clk(8)='1')then

x<=std_logic_vector("1111"&res1); 

else x<=std_logic_vector("0000"&res2) ;

end if;

end if;
end process;
END rtl;
