-- hds header_start
--
-- VHDL Entity InovateFPGA_de10.Neuron9.symbol
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 15:00:20 06/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Neuron9 IS
   PORT( 
      R0_0     : IN     std_logic_vector (7 DOWNTO 0);
      R0_1     : IN     std_logic_vector (7 DOWNTO 0);
      R0_2     : IN     std_logic_vector (7 DOWNTO 0);
      R0_3     : IN     std_logic_vector (7 DOWNTO 0);
      clk      : IN     std_logic;
      en       : IN     std_logic;
      rst      : IN     std_logic;
      w0       : IN     std_logic_vector (8 DOWNTO 0);
      w1       : IN     std_logic_vector (8 DOWNTO 0);
      w2       : IN     std_logic_vector (8 DOWNTO 0);
      w3       : IN     std_logic_vector (8 DOWNTO 0);
      RELU_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END Neuron9 ;

-- hds interface_end
--
-- VHDL Architecture InovateFPGA_de10.Neuron9.struct
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 15:00:20 06/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY InovateFPGA_de10;

ARCHITECTURE struct OF Neuron9 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL x0 : std_logic_vector(21 DOWNTO 0);
   SIGNAL x1 : std_logic_vector(21 DOWNTO 0);
   SIGNAL x2 : std_logic_vector(21 DOWNTO 0);
   SIGNAL x3 : std_logic_vector(21 DOWNTO 0);


   -- Component Declarations
   COMPONENT adder_9
   PORT (
      rst     : IN     std_logic ;
      clk     : IN     std_logic ;
      en      : IN     std_logic ;
      x0      : IN     std_logic_vector (21 DOWNTO 0);
      x1      : IN     std_logic_vector (21 DOWNTO 0);
      x2      : IN     std_logic_vector (21 DOWNTO 0);
      x3      : IN     std_logic_vector (21 DOWNTO 0);
      sum_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT mul_conv4
   PORT (
      rst           : IN     std_logic ;
      clk           : IN     std_logic ;
      in_filter_clk : IN     std_logic_vector (8 DOWNTO 0);
      in_image_clk  : IN     std_logic_vector (7 DOWNTO 0);
      x             : OUT    std_logic_vector (21 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : adder_9 USE ENTITY InovateFPGA_de10.adder_9;
   FOR ALL : mul_conv4 USE ENTITY InovateFPGA_de10.mul_conv4;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I1 : adder_9
      PORT MAP (
         rst     => rst,
         clk     => clk,
         en      => en,
         x0      => x0,
         x1      => x1,
         x2      => x2,
         x3      => x3,
         sum_out => RELU_out
      );
   I4 : mul_conv4
      PORT MAP (
         rst           => rst,
         clk           => clk,
         in_filter_clk => w2,
         in_image_clk  => R0_2,
         x             => x2
      );
   I2 : mul_conv4
      PORT MAP (
         rst           => rst,
         clk           => clk,
         in_filter_clk => w0,
         in_image_clk  => R0_0,
         x             => x0
      );
   I3 : mul_conv4
      PORT MAP (
         rst           => rst,
         clk           => clk,
         in_filter_clk => w1,
         in_image_clk  => R0_1,
         x             => x1
      );
   I8 : mul_conv4
      PORT MAP (
         rst           => rst,
         clk           => clk,
         in_filter_clk => w3,
         in_image_clk  => R0_3,
         x             => x3
      );

END struct;
