-- hds header_start
--
-- VHDL Entity InovateFPGA_de10.Neuron9_bd.symbol
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 17:38:10 04/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Neuron9_bd IS
   PORT( 
      master_clk : IN     std_logic;
      rst        : IN     std_logic;
      rx_uart    : IN     std_logic;
      tx_done    : OUT    std_logic;
      uart_tx1   : OUT    std_logic
   );

-- Declarations

END Neuron9_bd ;

-- hds interface_end
--
-- VHDL Architecture InovateFPGA_de10.Neuron9_bd.struct
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 17:38:10 04/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY InovateFPGA_de10;

ARCHITECTURE struct OF Neuron9_bd IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL R0_0     : std_logic_vector(7 DOWNTO 0);
   SIGNAL R0_1     : std_logic_vector(7 DOWNTO 0);
   SIGNAL R0_2     : std_logic_vector(7 DOWNTO 0);
   SIGNAL R0_3     : std_logic_vector(7 DOWNTO 0);
   SIGNAL RELU_en  : std_logic;
   SIGNAL relu_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL w0       : std_logic_vector(8 DOWNTO 0);
   SIGNAL w1       : std_logic_vector(8 DOWNTO 0);
   SIGNAL w2       : std_logic_vector(8 DOWNTO 0);
   SIGNAL w3       : std_logic_vector(8 DOWNTO 0);


   -- Component Declarations
   COMPONENT Neuron9
   PORT (
      R0_0    : IN     std_logic_vector (7 DOWNTO 0);
      R0_1    : IN     std_logic_vector (7 DOWNTO 0);
      R0_2    : IN     std_logic_vector (7 DOWNTO 0);
      R0_3    : IN     std_logic_vector (7 DOWNTO 0);
      clk     : IN     std_logic ;
      en      : IN     std_logic ;
      rst     : IN     std_logic ;
      w0      : IN     std_logic_vector (8 DOWNTO 0);
      w1      : IN     std_logic_vector (8 DOWNTO 0);
      w2      : IN     std_logic_vector (8 DOWNTO 0);
      w3      : IN     std_logic_vector (8 DOWNTO 0);
      sum_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT UART_TX_RX_final
   PORT (
      Relu_out   : IN     std_logic_vector (7 DOWNTO 0);
      master_clk : IN     std_logic ;
      rst        : IN     std_logic ;
      rx_uart    : IN     std_logic ;
      RELU_en    : OUT    std_logic ;
      W0         : OUT    std_logic_vector (8 DOWNTO 0);
      W1         : OUT    std_logic_vector (8 DOWNTO 0);
      W2         : OUT    std_logic_vector (8 DOWNTO 0);
      W3         : OUT    std_logic_vector (8 DOWNTO 0);
      dbus0      : OUT    std_logic_vector (7 DOWNTO 0);
      dbus1      : OUT    std_logic_vector (7 DOWNTO 0);
      dbus2      : OUT    std_logic_vector (7 DOWNTO 0);
      dbus3      : OUT    std_logic_vector (7 DOWNTO 0);
      tx_done    : OUT    std_logic ;
      uart_tx1   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Neuron9 USE ENTITY InovateFPGA_de10.Neuron9;
   FOR ALL : UART_TX_RX_final USE ENTITY InovateFPGA_de10.UART_TX_RX_final;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I1 : Neuron9
      PORT MAP (
         R0_0    => R0_0,
         R0_1    => R0_1,
         R0_2    => R0_2,
         R0_3    => R0_3,
         clk     => master_clk,
         en      => RELU_en,
         rst     => rst,
         w0      => w0,
         w1      => w1,
         w2      => w2,
         w3      => w3,
         sum_out => relu_out
      );
   I0 : UART_TX_RX_final
      PORT MAP (
         Relu_out   => relu_out,
         master_clk => master_clk,
         rst        => rst,
         rx_uart    => rx_uart,
         RELU_en    => RELU_en,
         W0         => w0,
         W1         => w1,
         W2         => w2,
         W3         => w3,
         dbus0      => R0_0,
         dbus1      => R0_1,
         dbus2      => R0_2,
         dbus3      => R0_3,
         tx_done    => tx_done,
         uart_tx1   => uart_tx1
      );

END struct;
