-- hds header_start
--
-- VHDL Architecture my_uart.register_8bits_en.rtl
--
-- Created:
--          by - scg.UNKNOWN (SCG-PC)
--          at - 21:24:03 22/05/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY register_8bits_en IS
port(rst,clk,en: in std_logic;
    
       data_in: in std_logic_vector(7 downto 0);
	   data_out: out std_logic_vector(7 downto 0));
-- Declarations

END register_8bits_en ;

-- hds interface_end
ARCHITECTURE rtl OF register_8bits_en IS
signal t: std_logic_vector(7 downto 0);
BEGIN
process(rst,clk)
begin
if(rst='0')then
--t<=(others=>'0');
t<="01000101";
elsif(rising_edge(clk))then
if(en='1')then
   t<= data_in;
end if;
end if;
end process;

data_out<=t;

END rtl;
