-- hds header_start
--
-- VHDL Entity InovateFPGA_de10.UART_RX.symbol
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 17:31:23 04/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY UART_RX IS
   PORT( 
      master_clk  : IN     std_logic;
      rst         : IN     std_logic;
      rx_uart     : IN     std_logic;
      data_outreg : OUT    std_logic_vector (7 DOWNTO 0);
      rx_done     : OUT    std_logic
   );

-- Declarations

END UART_RX ;

-- hds interface_end
--
-- VHDL Architecture InovateFPGA_de10.UART_RX.struct
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 17:31:23 04/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY InovateFPGA_de10;

ARCHITECTURE struct OF UART_RX IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk_100u : std_logic;
   SIGNAL data_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL en       : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL rx_done_internal : std_logic;


   -- Component Declarations
   COMPONENT clk_100us
   PORT (
      rst     : IN     std_logic ;
      clk     : IN     std_logic ;
      en      : IN     std_logic ;
      clk_out : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT register_8bits_en
   PORT (
      rst      : IN     std_logic ;
      clk      : IN     std_logic ;
      en       : IN     std_logic ;
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT uart_rx_fsm
   PORT (
      clk_100u   : IN     std_logic ;
      master_clk : IN     std_logic ;
      rst        : IN     std_logic ;
      rx_uart    : IN     std_logic ;
      data_out   : OUT    std_logic_vector (7 DOWNTO 0);
      en         : OUT    std_logic ;
      rx_done    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_100us USE ENTITY InovateFPGA_de10.clk_100us;
   FOR ALL : register_8bits_en USE ENTITY InovateFPGA_de10.register_8bits_en;
   FOR ALL : uart_rx_fsm USE ENTITY InovateFPGA_de10.uart_rx_fsm;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I0 : clk_100us
      PORT MAP (
         rst     => rst,
         clk     => master_clk,
         en      => en,
         clk_out => clk_100u
      );
   I2 : register_8bits_en
      PORT MAP (
         rst      => rst,
         clk      => master_clk,
         en       => rx_done_internal,
         data_in  => data_out,
         data_out => data_outreg
      );
   I1 : uart_rx_fsm
      PORT MAP (
         clk_100u   => clk_100u,
         master_clk => master_clk,
         rst        => rst,
         rx_uart    => rx_uart,
         data_out   => data_out,
         en         => en,
         rx_done    => rx_done_internal
      );

   -- Implicit buffered output assignments
   rx_done <= rx_done_internal;

END struct;
