-- hds header_start
--
-- VHDL Entity InovateFPGA_de10.UART_TX_RX_final.symbol
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 17:37:11 04/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY UART_TX_RX_final IS
   PORT( 
      Relu_out   : IN     std_logic_vector (7 DOWNTO 0);
      master_clk : IN     std_logic;
      rst        : IN     std_logic;
      rx_uart    : IN     std_logic;
      RELU_en    : OUT    std_logic;
      W0         : OUT    std_logic_vector (8 DOWNTO 0);
      W1         : OUT    std_logic_vector (8 DOWNTO 0);
      W2         : OUT    std_logic_vector (8 DOWNTO 0);
      W3         : OUT    std_logic_vector (8 DOWNTO 0);
      dbus0      : OUT    std_logic_vector (7 DOWNTO 0);
      dbus1      : OUT    std_logic_vector (7 DOWNTO 0);
      dbus2      : OUT    std_logic_vector (7 DOWNTO 0);
      dbus3      : OUT    std_logic_vector (7 DOWNTO 0);
      tx_done    : OUT    std_logic;
      uart_tx1   : OUT    std_logic
   );

-- Declarations

END UART_TX_RX_final ;

-- hds interface_end
--
-- VHDL Architecture InovateFPGA_de10.UART_TX_RX_final.struct
--
-- Created:
--          by - HoA.UNKNOWN (LAPTOP-6PPNGBRG)
--          at - 17:37:11 04/25/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY InovateFPGA_de10;

ARCHITECTURE struct OF UART_TX_RX_final IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D_in         : std_logic_vector(7 DOWNTO 0);
   SIGNAL Trans_Finish : std_logic;
   SIGNAL data_outreg  : std_logic_vector(7 DOWNTO 0);
   SIGNAL rx_done      : std_logic;
   SIGNAL tx_request   : std_logic;


   -- Component Declarations
   COMPONENT UART_RX
   PORT (
      master_clk  : IN     std_logic ;
      rst         : IN     std_logic ;
      rx_uart     : IN     std_logic ;
      data_outreg : OUT    std_logic_vector (7 DOWNTO 0);
      rx_done     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT UART_TX
   PORT (
      D_input      : IN     std_logic_vector (7 DOWNTO 0);
      master_clk   : IN     std_logic ;
      rst          : IN     std_logic ;
      tx_request   : IN     std_logic ;
      Trans_Finish : OUT    std_logic ;
      tx_done      : OUT    std_logic ;
      uart_tx      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT tx_rx_fsm
   PORT (
      Relu_out     : IN     std_logic_vector (7 DOWNTO 0);
      Trans_Finish : IN     std_logic ;
      data_outreg  : IN     std_logic_vector (7 DOWNTO 0);
      master_clk   : IN     std_logic ;
      rst          : IN     std_logic ;
      rx_done      : IN     std_logic ;
      D_in         : OUT    std_logic_vector (7 DOWNTO 0);
      RELU_en      : OUT    std_logic ;
      W0           : OUT    std_logic_vector (8 DOWNTO 0);
      W1           : OUT    std_logic_vector (8 DOWNTO 0);
      W2           : OUT    std_logic_vector (8 DOWNTO 0);
      W3           : OUT    std_logic_vector (8 DOWNTO 0);
      dbus0        : OUT    std_logic_vector (7 DOWNTO 0);
      dbus1        : OUT    std_logic_vector (7 DOWNTO 0);
      dbus2        : OUT    std_logic_vector (7 DOWNTO 0);
      dbus3        : OUT    std_logic_vector (7 DOWNTO 0);
      tx_request   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : UART_RX USE ENTITY InovateFPGA_de10.UART_RX;
   FOR ALL : UART_TX USE ENTITY InovateFPGA_de10.UART_TX;
   FOR ALL : tx_rx_fsm USE ENTITY InovateFPGA_de10.tx_rx_fsm;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I0 : UART_RX
      PORT MAP (
         master_clk  => master_clk,
         rst         => rst,
         rx_uart     => rx_uart,
         data_outreg => data_outreg,
         rx_done     => rx_done
      );
   I1 : UART_TX
      PORT MAP (
         D_input      => D_in,
         master_clk   => master_clk,
         rst          => rst,
         tx_request   => tx_request,
         Trans_Finish => Trans_Finish,
         tx_done      => tx_done,
         uart_tx      => uart_tx1
      );
   I2 : tx_rx_fsm
      PORT MAP (
         Relu_out     => Relu_out,
         Trans_Finish => Trans_Finish,
         data_outreg  => data_outreg,
         master_clk   => master_clk,
         rst          => rst,
         rx_done      => rx_done,
         D_in         => D_in,
         RELU_en      => RELU_en,
         W0           => W0,
         W1           => W1,
         W2           => W2,
         W3           => W3,
         dbus0        => dbus0,
         dbus1        => dbus1,
         dbus2        => dbus2,
         dbus3        => dbus3,
         tx_request   => tx_request
      );

END struct;
